# docker login https://registry.redhat.io
services:
  business_central:
    build: ./business-central
    image: business-central
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "9990:9990"
