# almost worked but business central ui not showing up
services:
  business_central:
    # docker login https://registry.redhat.io
    image: "registry.redhat.io/ibm-bamoe/bamoe-businesscentral-rhel8:8.0.6"
    # force emulation
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8778:8778"
